=== al-arroyo/UPM/PIAT/Segundo Parcial 21-22/graphs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.piat.dte.upm.es/examenJunio"
            xmlns:tns="http://www.piat.dte.upm.es/examenJunio"
            elementFormDefault="qualified">
    <xsd:element name="graphs">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="graph" type="tns:tipoGraph" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>       
    </xsd:element>

    <xsd:complexType name="tipoGraph">
        <xsd:sequence>
            <xsd:element name="tipoPostalCode" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>
                        Valor del nombre "postal-code" del objeto "@context"
                        En caso de que no exista dicho valor, no aparecerá este elemento.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="postalCode" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>
                        valor del nombre "postal-code" del objeto "address" descendiente del objeto "@graph".
                        En caso de que no exista dicho valor, no aparecerá este elemento.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:anyURI"/>
    </xsd:complexType>
</xsd:schema>

=== al-arroyo/UPM/PIAT/Segundo Parcial 21-22/salidaExamen.xml
<?xml version="1.0" encoding="UTF-8"?>
<pc:graphs 
	xmlns:pc="http://www.piat.dte.upm.es/examenJunio"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.piat.dte.upm.es/examenJunio graphs.xsd">
		<pc:graph id="https://datos.madrid.es/egob/catalogo/tipo/evento/11949320-alegria-cirque-du-soleil-circo-sol-.json">
			<pc:tipoPostalCode>vcard:postal-code</pc:tipoPostalCode>
			<pc:postalCode>28011</pc:postalCode>
		</pc:graph>
		<pc:graph id="https://datos.madrid.es/egob/catalogo/tipo/evento/11990810-asociacion-cultural-chilena-cal-canto.json">
			<pc:tipoPostalCode>vcard:postal-code</pc:tipoPostalCode>
			<pc:postalCode>28044</pc:postalCode>
		</pc:graph>
		<pc:graph id="https://datos.madrid.es/egob/catalogo/tipo/evento/11780613-aprende-bailar-marinera.json">
			<pc:tipoPostalCode>vcard:postal-code</pc:tipoPostalCode>
			<pc:postalCode>28037</pc:postalCode>
		</pc:graph>
		<pc:graph id="https://datos.madrid.es/egob/catalogo/tipo/evento/12006315-camino.json">
			<pc:tipoPostalCode>vcard:postal-code</pc:tipoPostalCode>
			<pc:postalCode>28023</pc:postalCode>
		</pc:graph>
<<<<<<< HEAD
=======
		<pc:graph id="https://datos.madrid.es/egob/catalogo/tipo/evento/11780613-aprende-bailar-marinera.json">
			<pc:tipoPostalCode>vcard:postal-code</pc:tipoPostalCode>
			<pc:postalCode>28037</pc:postalCode>
		</pc:graph>
>>>>>>> 100d6b52ea707b6d5effe89e2f9e7e101e124b5f
		<pc:graph id="https://datos.madrid.es/egob/catalogo/tipo/evento/11976655-aromas-danza.json">
			<pc:tipoPostalCode>vcard:postal-code</pc:tipoPostalCode>
			<pc:postalCode>28009</pc:postalCode>
		</pc:graph>
		<pc:graph id="https://datos.madrid.es/egob/catalogo/tipo/evento/11987250-bailando-versos.json">
			<pc:tipoPostalCode>vcard:postal-code</pc:tipoPostalCode>
			<pc:postalCode>28031</pc:postalCode>
		</pc:graph>
</pc:graphs>
